services:
  - type: web
    name: chatbot-api
    env: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 10000
    healthCheckPath: /docs
